### ISSUE TITLE
.

### ISSUE THREAD

**Issue by KamuiID** [Usergh0st/bspwm#1]

**Comment by Usergh0st** [comment]
Hello, is there a problem with the desktop environment?

**Comment by KamuiID** [comment]
Hello! So, I closed because I don't know if I did something wrong, but, when I run the steps, the bspwm doesn't appear to be available for selection, is like it's not installed, I ran in kali VM, it's necessary to run in native OS? I ran some others bspwm dotfiles and they worked.


Thanks

**Comment by Usergh0st** [comment]
Well I hope the problem has been solved, this works for virtual machines and native installations

**Comment by Usergh0st** [comment]
Hi,

Thank you so much for your kind words and appreciation for our customs. We
are glad that you like them.

Regarding the bspwm option not appearing after following the steps and
rebooting, we apologize for the inconvenience this may have caused you. We
understand that you're new to Linux customization and it can be a bit
challenging at times.

We appreciate you reaching out to us and letting us know about the issue.
We will look into it and try to find a solution for you.

Thank you once again for your support and patience.

Best regards,
[AlvinPix]

**Comment by KamuiID** [comment]
Thanks for the answer, here is print of the problem, if needed:
![Pasted image](https://github.com/AlvinPix/bspwm/assets/122818447/55a9a407-ba39-4e72-bd8a-7515fbc074b7)

**Comment by Usergh0st** [comment]
Hi,

Thanks for sharing the print of the problem. I'll make sure to keep it for
reference.

Best regards,

[AlvinPix]
