### ISSUE TITLE
Error en la instalacion

### ISSUE THREAD

**Issue by davidtriminio** [Usergh0st/bspwm#2]
Erase is control-H (^H).

 [i] Last step installing the powerlevel10k, fzf, sudo-plugin, and others for the root user

fatal: destination path '/root/powerlevel10k' already exists and is not an empty directory.

fatal: destination path 'shell-color-scripts' already exists and is not an empty directory.

fatal: destination path '/root/.fzf' already exists and is not an empty directory.
Downloading bin/fzf ...
  - Already exists
  - Checking fzf executable ... 0.45.0
Do you want to enable fuzzy auto-completion? ([y]/n) y
Do you want to enable key bindings? ([y]/n) y

Generate /root/.fzf.bash ... OK
Generate /root/.fzf.zsh ... OK

Do you want to update your shell configuration files? ([y]/n) y

Update /root/.bashrc:
  - [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    - Already exists: line #158 
                                                                             
Update /root/.zshrc:                                                         
  - [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh                                   
    + Added                                                                  
                                                                             
Finished. Restart your shell or reload config file.                          
   source ~/.bashrc  # bash                                                  
   source ~/.zshrc   # zsh                                                   
                                                                             
Use uninstall script to remove fzf.                                          
                                                                             
For more information, see: https://github.com/junegunn/fzf                   
                                                                             
fatal: destination path 'pipes.sh' already exists and is not an empty directory.        

![Screenshot_2024-01-11_12-06-33](https://github.com/AlvinPix/bspwm/assets/142177715/0ecdf83c-c634-42e8-8e9d-be55fc69eac3)

**Comment by Usergh0st** [comment]
"Hello, good, at first glance, it says that the directories already exist,
and that's why the errors. Anyway, in the future, I will update the
repository to add more features to this desktop environment. Thank you very
much for trying it."

**Comment by davidtriminio** [comment]
I appreciate your prompt response, I follow the instructions to the letter, but the problem is that it is installed and when I open my environment with bspwm only shows a wallpaper everything else is not displayed, what is the command to choose theme?
![image](https://github.com/AlvinPix/bspwm/assets/142177715/64091ee2-1e35-441a-975d-11f3c79368d2)

**Comment by Usergh0st** [comment]
Try restarting BSPWM; I believe it's done with the Win + Alt + R keys, or
alternatively, Win + Enter and then typing 'bspc -r' in the terminal.

**Comment by davidtriminio** [comment]
I just did both and it only changes the background of the screen. The polybar is not displayed

**Comment by XKl4us-X** [comment]
bro this question is very silly but where can I deactivate the images that appear every time I open the terminal?
![Captura de pantalla 2024-01-13 195125](https://github.com/AlvinPix/bspwm/assets/140129568/6d3329eb-3fcd-4b9c-a229-c435c9a091b4)

**Comment by Usergh0st** [comment]
> hermano esta pregunta es muy tonta pero ¿dónde puedo desactivar las imágenes que aparecen cada vez que abre el terminal? ![Captura de pantalla 2024-01-13 195125](https://private-user-images.githubusercontent.com/140129568/296523649-6d3329eb-3fcd-4b9c-a229-c435c9a091b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNTI1ODYsIm5iZiI6MTcwODA1MjI4NiwicGF0aCI6Ii8xNDAxMjk1NjgvMjk2NTIzNjQ5LTZkMzMyOWViLTNmY2QtNGI5Yy1hMjI5LWM0MzVjOWEwOTFiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQwMjU4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWY3NGI1YjE0YWYyYzFiZWM1NjNhNjRlMjYwODFlMjI1YjU3NTA3NjA2MDcwOWU2Y2NiMmNlOGY3YjRkMWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UfXUkcOejyDEtogdOiwzGjsc4vKnDbCJAumLWu4KdOw)

Hello, just edit the .zshrc file, there is an alias called colorscript below that line, this is the one you want, just comment it # and the scripts will stop appearing

![2024-02-15_23-01](https://github.com/AlvinPix/bspwm/assets/96206578/c1b242fa-a8c3-48c2-85df-64b25c66a6dc)

**Comment by Usergh0st** [comment]
> Acabo de hacer ambas cosas y solo cambia el fondo de la pantalla. La polibarra no se muestra

Hola el problema que tienes aun persiste, hice esto muy cuidadosamente para que no halla errores me puedes dar algo mas de informacion, primero estas usando kali en maquina virtual o tienes la instalación en un equipo físico

**Comment by XKl4us-X** [comment]
Thank you very much, this super well done environment I really liked but I'm still something new and could not find this, thank you very much was solved by commenting on the line. A taste excellent environment.
