### ISSUE TITLE
kitty running slow when doing super + Return

### ISSUE THREAD

**Issue by torturado** [Usergh0st/bspwm#3]
kitty has some latency when writing, like, it has a sec delay or something.

but if I execute kitty from qterminal goes perfect. Also, if I execute kitty from kitty it goes perfect. I tried everything on the internet to fix it but I can't

**Comment by torturado** [comment]
I tried to use a dualboot with this customization and worked perfect. So the problem is when using VM

**Comment by Usergh0st** [comment]
> I tried to use a dualboot with this customization and worked perfect. So the problem is when using VM

It should be noted that I made this configuration more for people who have Kali as their main operating system, as I use it, I would have to test it in virtual machines to see the errors it has in the environment.
